### ISSUE TITLE
Error in Loading Pre-trained Weights

### ISSUE THREAD

**Issue by Chen-Ziyang** [Davidczy/Uni4Eye_pp#3]
Hi, thank you for your released codes and model weights.
However, I encountered an error while trying to load the pre-trained weights from "uni4eye++_vitl.pth". 
The error message is as follows:

    RuntimeError: Error(s) in loading state_dict for MaskedAutoencoderViT_partial23D:
	    Missing key(s) in state_dict: "pos_embed2", "pos_embed3", "decoder_pos_embed2", "decoder_pos_embed3", "patch_embed.proj2.weight", "patch_embed.proj2.bias", "patch_embed.proj3.weight", "patch_embed.proj3.bias", "decoder_pred2.weight", "decoder_pred2.bias", "decoder_pred3.weight", "decoder_pred3.bias". 
	    Unexpected key(s) in state_dict: "pos_embed", "decoder_pos_embed", "decoder_pred.weight", "decoder_pred.bias", "patch_embed.proj.weight", "patch_embed.proj.bias". 

I wonder know if the weight file is correct and how to solve this problem.

**Comment by Davidczy** [comment]
Thank you for your interest in my work. This error is due to the fact that my code is the MICCAI paper version, but the model currently uploaded is the subsequent journal version model.

To fix this, you only need to add `import models_mymae `at the beginning of the main_pretrain_partial23D.py file, and then change `models_mymae23D` to `models_mymae` on line 173.

**Comment by Chen-Ziyang** [comment]
Thank you for your response. This issue has been resolved.
